4339project/config/routes.rb
Rails.application.routes.draw do
  resources :finances

  resources :quotes

  resources :dealerships

  resources :cars

  resources :staffs

  root 'dealerships#index'

end

4339project/app/models/dealership.rb
class Dealership < ActiveRecord::Base
belongs_to :quote
  def self.net_profit=
  Dealership.average('netprofit')  || 0

    end

end

4339project/app/controllers/dealerships_controller.rb
class DealershipsController < ApplicationController
  before_action :set_dealership, only: [:show, :edit, :update, :destroy]

  # GET /dealerships
  # GET /dealerships.json
  def index
    @dealerships = Dealership.all
  end

  # GET /dealerships/1
  # GET /dealerships/1.json
  def show
  end

  # GET /dealerships/new
  def new
    @dealership = Dealership.new
  end

  # GET /dealerships/1/edit
  def edit
  end

  # POST /dealerships
  # POST /dealerships.json
  def create
    @dealership = Dealership.new(dealership_params)

    respond_to do |format|
      if @dealership.save
        format.html { redirect_to @dealership, notice: 'Dealership was successfully created.' }
        format.json { render :show, status: :created, location: @dealership }
      else
        format.html { render :new }
        format.json { render json: @dealership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dealerships/1
  # PATCH/PUT /dealerships/1.json
  def update
    respond_to do |format|
      if @dealership.update(dealership_params)
        format.html { redirect_to @dealership, notice: 'Dealership was successfully updated.' }
        format.json { render :show, status: :ok, location: @dealership }
      else
        format.html { render :edit }
        format.json { render json: @dealership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dealerships/1
  # DELETE /dealerships/1.json
  def destroy
    @dealership.destroy
    respond_to do |format|
      format.html { redirect_to dealerships_url, notice: 'Dealership was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dealership
      @dealership = Dealership.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dealership_params
      params.require(:dealership).permit(:salestaxtotals, :netprofit, :salestaxprofit)
    end
end

4339project/app/helpers/dealerships_helper.rb
module DealershipsHelper
end

4339project/app/views/dealerships/_form.html.erb
<%= form_for(@dealership) do |f| %>
  <% if @dealership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dealership.errors.count, "error") %> prohibited this dealership from being saved:</h2>

      <ul>
      <% @dealership.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :salestaxtotals %><br>
    <%= f.number_field :salestaxtotals %>
  </div>
  <div class="field">
    <%= f.label :netprofit %><br>
    <%= f.number_field :netprofit %>
  </div>
  <div class="field">
    <%= f.label :salestaxprofit %><br>
    <%= f.number_field :salestaxprofit %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

4339project/app/views/dealerships/edit.html.erb
<h1>Editing Dealership</h1>

<%= render 'form' %>

<%= link_to 'Show', @dealership %> |
<%= link_to 'Back', dealerships_path %>

4339project/app/views/dealerships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dealership Report</h1>

<table>
  <thead>
    <tr>
      <th>Sales tax totals--</th>
      <th>Net profit--</th>
      <th>Sales tax profit--</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dealerships.each do |dealership| %>
      <tr>
        <td><%= number_to_currency(dealership.salestaxtotals) %></td>
        <td><%= number_to_currency(dealership.netprofit) %></td>
        <td><%= number_to_currency(dealership.salestaxprofit) %></td>
        <td><%= link_to 'Show', dealership %></td>
        <td><%= link_to 'Edit', edit_dealership_path(dealership) %></td>
        <td><%= link_to 'Destroy', dealership, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<th><b>Total Revenue: </b></th>
 <td>
 $765,435.00
</td>


<br>

<th><b>Gross Profit: </b></th>
 <td>
  $165,435.00
</td>

<br>

<th><b>Total Sales Tax: </b></th>
 <td>
  $65,435.00
</td>

<br>

<%= link_to 'New Dealership', new_dealership_path %>

4339project/app/views/dealerships/new.html.erb
<h1>New Dealership</h1>

<%= render 'form' %>

<%= link_to 'Back', dealerships_path %>

4339project/app/views/dealerships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Salestaxtotals:</strong>
  <%= number_to_currency(@dealership.salestaxtotals) %>
</p>

<p>
  <strong>Netprofit:</strong>
  <%= number_to_currency(@dealership.netprofit) %>
</p>

<p>
  <strong>Salestaxprofit:</strong>
  <%= number_to_currency(@dealership.salestaxprofit) %>
</p>

<%= link_to 'Edit', edit_dealership_path(@dealership) %> |
<%= link_to 'Back', dealerships_path %>