4339project/config/routes.rb
Rails.application.routes.draw do
  resources :finances

  resources :quotes

  resources :dealerships

  resources :cars

  resources :staffs

  root 'dealerships#index'

end

4339project/app/models/finance.rb
class Finance < ActiveRecord::Base
  belongs_to :quote

  def self.calculate_population_table(starting_population = 0,time_frame = 0,growth_rate = 0)
    Rails.logger.debug "Inputs: #{starting_population} #{time_frame} #{growth_rate}"
    population = []
    (0..time_frame).each do |t|
      population << starting_population * Math.exp(growth_rate * t)
    end
    return population # the word return is optional - could just put population
  end

  def calculate_population_table
    return self.class.calculate_population_table(self.starting_population,self.time_frame,self.growth_rate)
  end
end

4339project/app/controllers/finances_controller.rb
class FinancesController < ApplicationController
  before_action :set_finance, only: [:show, :edit, :update, :destroy]

  # GET /finances
  # GET /finances.json
  def index
    @finances = Finance.all
  end

  # GET /finances/1
  # GET /finances/1.json
  def show
  end

  # GET /finances/new
  def new
    @finance = Finance.new
  end

  # GET /finances/1/edit
  def edit
  end

  # POST /finances
  # POST /finances.json
  def create
    @finance = Finance.new(finance_params)

    respond_to do |format|
      if @finance.save
        format.html { redirect_to @finance, notice: 'Finance was successfully created.' }
        format.json { render :show, status: :created, location: @finance }
      else
        format.html { render :new }
        format.json { render json: @finance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /finances/1
  # PATCH/PUT /finances/1.json
  def update
    respond_to do |format|
      if @finance.update(finance_params)
        format.html { redirect_to @finance, notice: 'Finance was successfully updated.' }
        format.json { render :show, status: :ok, location: @finance }
      else
        format.html { render :edit }
        format.json { render json: @finance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /finances/1
  # DELETE /finances/1.json
  def destroy
    @finance.destroy
    respond_to do |format|
      format.html { redirect_to finances_url, notice: 'Finance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_finance
      @finance = Finance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def finance_params
      params.require(:finance).permit(:price, :interest, :year_plan)
    end
end

4339project/app/helpers/finances_helper.rb
module FinancesHelper
end

4339project/app/views/finances/_form.html.erb
<%= form_for(@finance) do |f| %>
  <% if @finance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@finance.errors.count, "error") %> prohibited this finance from being saved:</h2>

      <ul>
      <% @finance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :interest %><br>
    <%= f.select(:interest, ['4%','6%','8%'], {}, { :class => 'interest' }) %>
  </div>
  <div class="field">
    <%= f.label :year_plan %><br>
    <%= f.select(:year_plan, ['2','4','6'], {}, { :class => 'year_plan' }) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

4339project/app/views/finances/edit.html.erb
<h1>Editing Finance</h1>

<%= render 'form' %>

<%= link_to 'Show', @finance %> |
<%= link_to 'Back', finances_path %>

4339project/app/views/finances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Finances</h1>

<table>
  <thead>
    <tr>
      <th>Price</th>
      <th>Interest</th>
      <th>Year plan</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @finances.each do |finance| %>
      <tr>
        <td><%=number_to_currency(finance.price)%></td>
        <td><%= finance.interest %></td>
        <td><%= finance.year_plan %></td>
        <td><%= link_to 'Show', finance %></td>
        <td><%= link_to 'Edit', edit_finance_path(finance) %></td>
        <td><%= link_to 'Destroy', finance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Finance', new_finance_path %>

4339project/app/views/finances/new.html.erb
<h1>New Finance</h1>

<%= render 'form' %>

<%= link_to 'Back', finances_path %>

4339project/app/views/finances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@finance.price) %>
</p>

<p>
  <strong>Interest:</strong>
  <%= @finance.interest %>
</p>

<p>
  <strong>Year plan:</strong>
  <%= @finance.year_plan %>
</p>

<%= link_to 'Edit', edit_finance_path(@finance) %> |
<%= link_to 'Back', finances_path %>